parameters:
  app.log_file_path: '/var/www/source/log/oe_examples_module.log'
  env(OEEM_SHOP_NAME): 'OXID eShop name not overwritten by .env file'

imports:
  - { resource: src/Greeting/services.yaml }
  - { resource: src/Logging/services.yaml }
  - { resource: src/ProductVote/services.yaml }
  - { resource: src/Tracker/services.yaml }
  - { resource: src/ApiEntrypoint/services.yaml }

services:

  _defaults:
    public: false
    autowire: true
#    This is how you can bind shop registry services to your services
#    bind:
#      OxidEsales\Eshop\Core\Language: '@=service("OxidEsales\\ExamplesModule\\Core\\Registry").getLang()'
#      OxidEsales\Eshop\Core\Session: '@=service("OxidEsales\\ExamplesModule\\Core\\Registry").getSession()'

  OxidEsales\ExamplesModule\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true
