services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ExamplesModule\ApiEntrypoint\CustomerGroup\Dao\CustomerGroupCountDaoInterface:
    class: OxidEsales\ExamplesModule\ApiEntrypoint\CustomerGroup\Dao\CustomerGroupCountDao

  OxidEsales\ExamplesModule\ApiEntrypoint\CustomerGroup\Service\CustomerGroupServiceInterface:
    class: OxidEsales\ExamplesModule\ApiEntrypoint\CustomerGroup\Service\CustomerGroupService

  OxidEsales\ExamplesModule\ApiEntrypoint\CustomerGroup\Controller\CustomerGroupApiController:
    public: true
