services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ExamplesModule\ApiEntrypoint\UserInfo\Dao\SessionUserDaoInterface:
    class: OxidEsales\ExamplesModule\ApiEntrypoint\UserInfo\Dao\SessionUserDao

  OxidEsales\ExamplesModule\ApiEntrypoint\UserInfo\Service\UserInfoServiceInterface:
    class: OxidEsales\ExamplesModule\ApiEntrypoint\UserInfo\Service\UserInfoService

  OxidEsales\ExamplesModule\ApiEntrypoint\UserInfo\Controller\UserInfoApiController:
    public: true
