services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ExamplesModule\ProductSearch\Service\PromotedProductSearchService:
    arguments:
      $promotedProductId: '%env(OEEM_PROMOTED_PRODUCT_ID)%'

  OxidEsales\EshopCommunity\Internal\Domain\Product\Search\ProductSearchServiceInterface:
    alias: OxidEsales\ExamplesModule\ProductSearch\Service\PromotedProductSearchService
    public: true

  OxidEsales\ExamplesModule\ProductSearch\Subscriber\SearchLoggingSubscriber:
    tags:
      - { name: kernel.event_subscriber }
